export const DATA = [
    { id: 1, month: "Jan", gain: 58 },
    { id: 2, month: "Feb", gain: 53 },
    { id: 3, month: "Mar", gain: 72 },
    { id: 4, month: "Apr", gain: 72 },
    { id: 5, month: "May", gain: 91 },
    { id: 6, month: "Jun", gain: 34 },
    { id: 7, month: "Jul", gain: 67 },
    { id: 8, month: "Aug", gain: 45 },
    { id: 9, month: "Sep", gain: 69 },
    { id: 10, month: "Oct", gain: 53 },
    { id: 11, month: "Nov", gain: 54 },
    { id: 12, month: "Dec", gain: 76 },
];
import resi from "./assets/resi.png";
export const DATA2 = [{
        id: 1,
        nom: "Danubius hotel regent park",
        location: "Abidjan, Cocodi",
        owner: "Franck kelkun",
        prix: "10 000",
        payment: "Paypal",
        date: "12 jan 2023",
        email: "franck@email.com",
        status: "En attente",
        img: resi,
    },
    {
        id: 2,
        nom: "Danubius hotel regent park",
        location: "Abidjan, Cocodi",
        owner: "Franck kelkun",
        prix: "10 000",
        payment: "Paypal",
        date: "12 jan 2023",
        status: "En attente",
        img: resi,
    },
    {
        id: 3,
        nom: "Danubius hotel regent park",
        location: "Abidjan, Cocodi",
        owner: "Franck kelkun",
        prix: "10 000",
        payment: "Paypal",
        date: "12 jan 2023",
        status: "En attente",
        img: resi,
    },
    {
        id: 4,
        nom: "Danubius hotel regent park",
        location: "Abidjan, Cocodi",
        owner: "Franck kelkun",
        prix: "10 000",
        payment: "Paypal",
        date: "12 jan 2023",
        status: "En attente",
        img: resi,
    },
    {
        id: 5,
        nom: "Danubius hotel regent park",
        location: "Abidjan, Cocodi",
        owner: "Franck kelkun",
        prix: "10 000",
        payment: "Paypal",
        date: "12 jan 2023",
        status: "En attente",
        img: resi,
    },
    {
        id: 6,
        nom: "Danubius hotel regent park",
        location: "Abidjan, Cocodi",
        owner: "Franck kelkun",
        prix: "10 000",
        payment: "Paypal",
        date: "12 jan 2023",
        status: "En attente",
        img: resi,
    },
    {
        id: 7,
        nom: "Danubius hotel regent park",
        location: "Abidjan, Cocodi",
        owner: "Franck kelkun",
        prix: "10 000",
        payment: "Paypal",
        date: "12 jan 2023",
        status: "En attente",
        img: resi,
    },
    {
        id: 8,
        nom: "Danubius hotel regent park",
        location: "Abidjan, Cocodi",
        owner: "Franck kelkun",
        prix: "10 000",
        payment: "Paypal",
        img: resi,
    },
];